[[GraphicsMagick]]
arch = "aarch64"
git-tree-sha1 = "f2604c50aa6dfc3b2cf4b9eef1360a90364ef5aa"
os = "macos"

    [[GraphicsMagick.download]]
    sha256 = "d726d7f26b0260f863939fbf88627bb951000bda2fb92e9efaa316b5d4905e17"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.aarch64-apple-darwin.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ff5c61d294457ae084fc51a412b8f3d38e8ad00"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "95fb77c72d4550156b79e46bcc5fadfeb00f3d6dade3fc820f11a2ea3b4fe16f"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.aarch64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e09bb6ca624ff5a4885889bc83b1703cb42bf818"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "bcc3dd1ea353e990dec4b769aaa22621deb5f2c6c0015e9d6fe949b07b26c0c8"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.aarch64-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "aarch64"
git-tree-sha1 = "fd7ab1257f381d74ada3a5b2a202409b00e29e25"
os = "freebsd"

    [[GraphicsMagick.download]]
    sha256 = "f57b08fa960d7484a85235aad091cfb2c18fd70d5e90490f96d895efd82597ca"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.aarch64-unknown-freebsd.tar.gz"
[[GraphicsMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "557b8b3a924113eef782fbe29511cf0a27b817cf"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "456c328731f1c0a948f014b8a1639fa4bf7aedef613c74678675c19ef4a69237"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c24f5a0284d926836eb8089b4978d5df00976d7e"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "07782cf7e609b5e4b3a50c93b8723982a9441a2a286c98f0d01af41991fe8a22"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71fb2a96a36c62cf79746d0b6c415a2915abbee4"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "f141cfd6369515e33bfb1abd0b747c69169a3d6b0ae9a29fa13da482efb00e51"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "692198f269ecc41cb0cdd3f3ce626294f671e39d"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "4825aa6d8ced82234a27fff6c6d54aa90feb36104e6b5a4c888c055b9cef71dd"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "549f3dc2f2e78c951c47f8e8a6f7e7ab77470a6a"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "63bbcddc379e34a24b50c8afd42abeda8ffc86d226bb330a71a080955d61bd00"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.i686-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa0cbfcce70789720ab9b6f67eee2749abdb0667"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "6aba096e1a554eaeba639676f416630b1f892b2dcc0e47018ef28f44d93c9cf5"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.i686-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84250db3a055f393eb061b7406114ac84b32652b"
os = "windows"

    [[GraphicsMagick.download]]
    sha256 = "3557743c6329869360e8caf3bdcbf2a205cc6b5591d2173493480741309f0f64"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.i686-w64-mingw32-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05b1b254d8dba74762f2e3d490bf8164335d1717"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "3e4e1138a40e2bc3c5f62401a9542a9171f561e297a1600627a8204bc821cdda"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb146ef80d4568b50ea9f7de57c24b87fbd65f18"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "47b98642c663070f6c708761108123a5aebfe3d4d6b33c6f7272cea0ae6c6f7e"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.riscv64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
git-tree-sha1 = "ed4aaa2fbf2288840b8cca67b24a90b773fa23e8"
os = "macos"

    [[GraphicsMagick.download]]
    sha256 = "c12f3e48d0aa54237675f9560bbb50040d4f6d9bd3e3ae897db996d44427f34c"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.x86_64-apple-darwin.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2339afe2aab441f44b2e73b1a8cccbb3dd4e1a5"
libc = "glibc"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "4819352e5a15d6d4696061958dfc009ab4c5fcd38ba69c974f625aa5bc512158"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.x86_64-linux-gnu-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4929f66c65a13f8668a1b10aaff57449e2cf17ea"
libc = "musl"
os = "linux"

    [[GraphicsMagick.download]]
    sha256 = "47d3b1c9198a89bed596fa8b4fdafcd0b6c34cc40de8f10e178387ae4358264e"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.x86_64-linux-musl-cxx11.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
git-tree-sha1 = "c1cf233cce06de0e774fa79ee5b45c884690614f"
os = "freebsd"

    [[GraphicsMagick.download]]
    sha256 = "78b509ed4e0c562cf82ec994b194bee5c840294a928e8c5bc6d331447c3faf38"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.x86_64-unknown-freebsd.tar.gz"
[[GraphicsMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c8e828511a5bc072e968602a54b9fd743917f16"
os = "windows"

    [[GraphicsMagick.download]]
    sha256 = "621f15647dec2e54badae9b8e2a632ef5896d73a43821949ea6ecdb186ef56b3"
    url = "https://github.com/JuliaBinaryWrappers/GraphicsMagick_jll.jl/releases/download/GraphicsMagick-v1.3.48+0/GraphicsMagick.v1.3.48.x86_64-w64-mingw32-cxx11.tar.gz"
